name: Preflight (dry-run)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build & package (dry-run)
        run: |
          set -euo pipefail
          cargo build --all-features
          cargo publish --dry-run